name: Generate api docs use dokka

on:
  push:
    branches:
      - main
      - release
      - develop

jobs:
  docs_job:
    name: gradle build api docs use dokka
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Push image to DockerHub
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: ${{secrets.DOCKERHUB_USERNAME}}/lattice-kt-docs:v1.0.0
          push: true%